// <auto-generated />
namespace AllMixedUp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GlazeIngredient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GlazeIngredient));
        
        string IMigrationMetadata.Id
        {
            get { return "202105032031029_GlazeIngredient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
