// <auto-generated />
namespace AllMixedUp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202104132231495_UserDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
